##SpringDatasources
#spring.datasource.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
##MyBatis
#mybatis.type-aliases-package=com.jxnudekt.server.entity
#mybatis.mapper-locations=classpath:mapper/*.xml

server:
  port: 80

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mini_programs_jxnudekt?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&useSSL=true"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss    #格式化时间
    time-zone: GMT+8                    #时差问题

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jxnudekt.server.entity
  configuration:
    map-underscore-to-camel-case: true
#打印SQL
logging:
  level:
    com.jxnudekt.server.dao: debug